google.maps.__gjsload__('map', function(_){'use strict';var uA=function(a,b){return new _.ft(_.P(a.j,1)[b])},vA=function(a){this.j=a||[]},wA=function(a){this.j=a||[]},xA=function(a,b){for(var c=0,d=_.fd(a.j.j,1);c<d;c++){var e=uA(a.j,c);0==e.getType()&&(e.j[2]=b)}},yA=function(a){var b=Math.round(1E7*a);return 0>a?b+4294967296:b},zA=function(a,b){for(var c=a.H.j[7],c=_.P((c?new _.Ve(c):_.Oi).j,0).slice(),d=0;d<c.length;++d)c[d]+="deg="+b+"&";return c},AA=function(a){a.j[4]=a.j[4]||[];return new _.ht(a.j[4])},BA=function(a,b){return _.bl(a.get("projection"),
b,a.get("zoom"),a.get("offset"),a.get("center"))},CA=function(){var a=_.R;a.j[1]=a.j[1]||[];return new _.Xe(a.j[1])},DA=function(a){return(a=a.j[1])?new _.Ve(a):_.Ni},EA=function(a){a=a.j[14];return null!=a?a:0},FA=function(a,b){return new vA(_.P(a.j,4)[b])},GA=function(a,b){return _.P(a.j,5)[b]},HA=function(a){return(a=a.j[1])?new _.Ue(a):_.Mi},IA=function(a){return(a=a.j[0])?new _.Ue(a):_.Li},JA=function(a){a=a.j[1];return null!=a?a:0},KA=function(a){a=a.j[0];return null!=a?a:0},LA=function(a){this.j=
a||[]},MA=function(a,b){for(var c=a.length,d=_.ya(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0},NA=function(a,b){for(var c=0,d=a.H,e=a.j,f=0,g;g=b[f++];)if(a.intersects(g)){var h=g.H,l=g.j,n=0;if(_.Uj(g,a))return 1;n=e.contains(l.j)&&l.contains(e.j)&&!_.Cd(e,l)?_.Dd(l.j,e.H)+_.Dd(e.j,l.H):_.Dd(e.contains(l.j)?l.j:e.j,e.contains(l.H)?l.H:e.H);c+=n*(Math.min(d.j,h.j)-Math.max(d.H,h.H))}return c/=_.Fd(d)*_.Bd(e)},OA=function(a,b){var c=a.x,d=a.y;switch(b){case 90:a.x=
d;a.y=256-c;break;case 180:a.x=256-c;a.y=256-d;break;case 270:a.x=256-d,a.y=c}},PA=function(a,b,c,d,e,f,g,h){this.Ja=a.Ja;this.zoom=a.zoom;this.j=a;this.T=b;this.ma=c;this.qa=d;this.V=e;this.S=f;this.W=g;this.R=_.za(h)?h:null;this.H="";this.bc()},QA=function(a,b,c,d,e){this.Ja=a;this.zoom=b;this.H=c;this.j=d.slice(0);this.R=e&&e.fh||_.ta},RA=function(){this.maxZoom=this.minZoom=-1;this.j=[];this.hb=[]},SA=function(a){this.R=a;this.j=null;this.set("idle",!0)},TA=function(){var a=!1;return function(b,
c){if(b&&c){if(.999999>NA(b,c))return a=!1;var d=_.al(b,(_.Yz-1)/2);return.999999<NA(d,c)?a=!0:a}}},UA=function(){return function(a,b){return a&&b?.9<=NA(a,b):void 0}},VA=_.oa("j"),$A=function(a){for(var b=[],c=0;c<_.w(a);++c){var d,e=a[c].elementType;d=a[c].stylers;var f=[],g;g=(g=a[c].featureType)&&WA[g.toLowerCase()];(g=null!=g?g:null)&&f.push("s.t:"+g);(e=e&&XA[e.toLowerCase()]||null)&&f.push("s.e:"+e);for(e=0;e<_.w(d);++e){a:{g=d[e];var h=void 0;for(h in g){var l=g[h],n=h&&YA[h.toLowerCase()]||
null;if(n&&(_.y(l)||_.Ua(l)||_.Wa(l))&&l){"color"==h&&ZA.test(l)&&(l="#ff"+l.substr(1));g="p."+n+":"+l;break a}}g=void 0}g&&f.push(g)}(d=f.join("|"))&&b.push(d)}a=b.join(",");return 1E3>=a.length?a:""},aB=_.oa("H"),bB=function(a,b){var c=a.T,d=a.H.get(b);c&&c instanceof _.Hw&&c.j&&(c.j.unbindAll(),a.unbind("mapType"));d&&d instanceof _.Hw&&d.j?(c=d.j,c.bindTo("heading",a),c.bindTo("tilt",a),a.bindTo("mapType",c)):a.set("mapType",d)},eB=function(a,b,c){var d=this;this.R=a;this.H=b;this.W=c;_.F.bind(b,
"insert_at",d,d.S);_.F.bind(b,"remove_at",d,d.T);_.F.bind(b,"set_at",d,d.V);this.j=[];d.H.forEach(function(a){a=cB(d,a);d.j.push(a)});dB(d)},dB=function(a){_.A(a.j,function(a,c){a.set("zIndex",c)})},cB=function(a,b){if(b){var c;switch(b.Za){case "roadmap":c="Otm";break;case "satellite":c="Otk";break;case "hybrid":c="Oth";break;case "terrain":c="Otr";break;default:c=b instanceof _.Ng?"Ots":"Oto"}a.W(c)}c=new _.Lw(a.R,null);c.bindTo("size",a);c.bindTo("zoom",a);c.bindTo("offset",a);c.bindTo("projectionBounds",
a);c.set("mapType",b);c.listener=b&&_.F.forward(c,"tilesloaded",b);return c},fB=function(a){a.release();a.listener&&(_.F.removeListener(a.listener),delete a.listener)},gB=function(a,b,c,d){function e(){if(!g.j&&!g.H){var n=c.get(),p=b.get("center"),q=b.get("zoom");null!=q&&p&&n&&n.width&&n.height&&(c.removeListener(e),h.remove(),l.remove(),d.size=n.width+"x"+n.height,d.hadviewport=f,g.H=p,g.T=q,g.j=_.hg("map2",{startTime:f?a:void 0,np:d}))}}this.ra=b;this.R={};this.T=this.H=this.j=null;this.S=!1;
var f=!0,g=this,h=b.addListener("center_changed",e),l=b.addListener("zoom_changed",e);c.addListener(e);e();f=!1},hB=function(a,b,c){!a.j||a.R[b]||a.S||(a.H.j(a.ra.get("center"))&&a.T==a.ra.get("zoom")?(a.R[b]=!0,c.call(a)):a.S=!0)},iB=function(a,b){hB(a,"staticmap",function(){var a={staticmap:b};hB(this,"firstpixel",function(){a.firstpixel=b});hB(this,"allpixels",function(){a.allpixels=b});_.fg(this.j,a)})},kB=function(a){var b={};b.firstmap=jB;b.hdpi=1<_.$k();b.mob=!_.X.W;b.staticmap=a;return b},
lB=function(a,b){this.R=a;this.S=b},mB=function(a,b){var c=window.document.createElement("div");_.$l(c);_.em(c,0);b(c);a.appendChild(c);this.set("div",c)},oB=function(a,b){this.j=function(c,d,e,f,g){var h;a:{if(!(7>d)){var l=1<<d-7;h=c.x/l;for(var l=c.y/l,n=0;n<nB.length;++n)if(h>=nB[n].Zf&&h<=nB[n].Yf&&l>=nB[n].ag&&l<=nB[n].$f){h=!0;break a}}h=!1}return h?b.j(c,d,e,f,g):a.j(c,d,e,f,g)}},pB=function(a,b){this.R=b||new _.Kf;this.j=new _.xd(a%360,45);this.S=new _.M(0,0);this.H=!0},qB=function(a,b,c,
d,e,f){this.j=function(g,h,l,n,p){return new PA(_.uw(g,h,l,n,p),a,_.Ag,b,c,d,e,f)}},rB=function(a){this.j=function(b,c,d,e,f){function g(){f&&f.Lc&&l.wc()&&f.Lc()}var h=_.ol(a,function(a,h){return a.j(b,c,d,e,{Fg:f&&f.Fg,Lc:g,zIndex:h})}),l=new QA(b,c,e,h,{fh:f&&f.fh});return l}},tB=function(a,b){this.H=b;this.j=360/b.length;this.R=a;sB(this)},sB=function(a){var b=a.get("heading")||0,c=a.R,d=a.get("tilt");d?c=a.H[b/a.j]:0==d&&0!=b&&a.set("heading",0);c!=a.get("mapType")&&a.set("mapType",c)},uB=function(a,
b,c,d){this.j=[];for(var e=0;e<_.w(a);++e){var f=a[e],g=new RA,h=f.j[2];g.minZoom=(null!=h?h:0)||0;h=f.j[3];g.maxZoom=(null!=h?h:0)||d;for(h=0;h<_.fd(f.j,5);++h)g.j.push(GA(f,h));for(h=0;h<_.fd(f.j,4);++h){var l=_.Jk(b,new _.Gd(new _.I(KA(IA(FA(f,h)))/1E7,JA(IA(FA(f,h)))/1E7),new _.I(KA(HA(FA(f,h)))/1E7,JA(HA(FA(f,h)))/1E7)),g.maxZoom);g.hb[h]=new _.Lf([new _.M(Math.floor(l.ua/c.width),Math.floor(l.va/c.height)),new _.M(Math.floor(l.Aa/c.width),Math.floor(l.Ba/c.height))])}this.j.push(g)}},vB=function(){var a=
new VA(UA()),b={};b.obliques=new VA(TA());b.report_map_issue=a;return b},wB=function(a,b){var c=a.__gm,d=new eB(b,a.overlayMapTypes,_.ul(_.$m,a));d.bindTo("size",c);d.bindTo("zoom",c);d.bindTo("offset",c);d.bindTo("projectionBounds",c)},xB=function(a){var b=new SA(300);b.bindTo("input",a,"bounds");_.F.addListener(b,"idle_changed",function(){b.get("idle")&&_.F.trigger(a,"idle")})},yB=function(a){if(a&&_.Vl(a.getDiv())&&(_.El()||_.Dl())){_.$m(a,"Tdev");var b=window.document.querySelector('meta[name="viewport"]');
(b=b&&b.content)&&b.match(/width=device-width/)&&_.$m(a,"Mfp")}},zB=function(a,b){function c(){var c=b.get("mapType");if(c)switch(c.Za){case "roadmap":_.$m(a,"Tm");break;case "satellite":c.ta&&_.$m(a,"Ta");_.$m(a,"Tk");break;case "hybrid":c.ta&&_.$m(a,"Ta");_.$m(a,"Th");break;case "terrain":_.$m(a,"Tr");break;default:_.$m(a,"To")}}c();_.F.addListener(b,"maptype_changed",c)},AB=function(a){var b=new aB(a.mapTypes);b.bindTo("bounds",a);b.bindTo("heading",a);b.bindTo("mapTypeId",a);b.bindTo("tilt",a.__gm);
return b},CB=function(a,b,c){_.Ja(_.$g,function(d,e){b.set(e,BB(a,e,{Zm:c}))})},DB=function(a,b){this.j=a;this.H=b},EB=function(a){this.j=a;a.addListener(function(){this.notify("style")},this)},FB=function(a,b){function c(c){c=b.getAt(c);if(c instanceof _.Ng){var e=new _.H,f=c.get("styles");e.set("apistyle",$A(f));e=BB(a,c.j,{Bm:e});c.T=(0,_.u)(e.T,e)}}_.F.addListener(b,"insert_at",c);_.F.addListener(b,"set_at",c);b.forEach(function(a,b){c(b)})},HB=function(a){var b;b=(b=window.navigator.connection||
window.navigator.mozConnection||window.navigator.webkitConnection||null)&&b.type;_.$m(a,"Nt",b&&GB[b]||"-na")},IB=function(a,b,c){if((_.El()||_.Dl())&&_.nm()){_.$m(b,"Mmni");var d=window.setInterval(function(){var e;e=a.j.getBoundingClientRect();if(e=!(0>=e.top-5&&0>=e.left-5&&e.height+5>=window.document.body.scrollHeight&&e.width+5>=window.document.body.scrollWidth))e=a.j.getBoundingClientRect(),e=0>=e.top-5&&0>=e.left-5&&e.bottom+5>=window.innerHeight&&e.right+5>=window.innerWidth&&(!c||c());e&&
(_.$m(b,"Mmus"),window.clearInterval(d))},1E3)}},JB=_.oa("j"),KB=function(a){this.j=a;_.F.bind(this.j,"set_at",this,this.H);_.F.bind(this.j,"insert_at",this,this.H);this.H()},LB=function(a){var b=[];a.j&&a.j.forEach(function(a){a&&b.push(a)});return b.join(", ")},MB=function(){var a,b=new _.H;b.bounds_changed=function(){var c=b.get("bounds");c?a&&_.Ej(a,c)||(a=_.Mf(c.ua-512,c.va-512,c.Aa+512,c.Ba+512),b.set("boundsQ",a)):b.set("boundsQ",c)};return b},NB=function(){this.V=new _.Jf;this.S={};this.R=
{}},OB=_.k(),QB=function(){PB(this)},PB=function(a){var b=new _.lw(a.get("minZoom")||0,a.get("maxZoom")||30),c=a.get("mapTypeMinZoom"),d=a.get("mapTypeMaxZoom"),e=a.get("trackerMaxZoom");_.y(c)&&(b.min=Math.max(b.min,c));_.y(e)?b.max=Math.min(b.max,e):_.y(d)&&(b.max=Math.min(b.max,d));a.set("zoomRange",b)},RB=_.k(),SB=function(a,b,c,d,e,f,g,h){var l=c.__gm,n=new _.Xx(c,a,b,!!c.j,e,l,d,g,(0,_.u)(f.j,f),h);n.bindTo("draggingCursor",c);n.bindTo("draggableMap",c,"draggable");_.F.addListener(c,"zoom_changed",
function(){n.get("zoom")!=c.get("zoom")&&n.set("zoom",c.get("zoom"))});n.set("zoom",c.get("zoom"));n.bindTo("disablePanMomentum",c);n.bindTo("projectionTopLeft",e);n.bindTo("draggableCursor",l,"cursor");d.bindTo("zoom",n);e.bindTo("zoom",n);return n},TB=function(a,b,c,d){var e=new gB(a,b,c,kB(!!d));jB=!1;d&&_.Vj(d,function g(a){a&&(d.removeListener(g),iB(e,a))});_.F.addListenerOnce(b,"tilesloaded",(0,_.u)(e.W,e));return e},UB=function(a,b,c,d){return d?new lB(a,function(){return b}):_.dg[23]?new lB(a,
function(a){var d=c.get("scale");return 2==d||4==d?b:a}):a},VB=function(a,b){var c=a.__gm,d=new mB(b,(0,_.u)(_.fm.H,_.fm));d.bindTo("center",a);d.bindTo("projectionBounds",c);d.bindTo("offset",c);return d},WB=_.oa("j"),XB=function(a,b,c){var d=_.Hj(),e=_.kf(_.R);this.ra=b;this.j=c;this.H=new _.Kf;this.R=_.hf(e);this.S=_.jf(e);this.V=EA(d);this.T=_.Lj(d);this.W=new _.pw(a,d,e);b={};c=0;for(d=_.fd(a.j,5);c<d;++c){var e=c,e=new LA(_.P(a.j,5)[e]),f;f=e.j[1];f=null!=f?f:0;b[f]=b[f]||[];b[f].push(e)}this.ma=
new uB(b[1],this.H,new _.N(256,256),22);a.j[1]=a.j[1]||[];a.j[7]=a.j[7]||[]},YB=function(a,b,c,d){d=d||{};var e=_.y(d.heading),f=c?(0,_.u)(c.T,c):_.pa(0);c=("hybrid"==b&&!e||"terrain"==b||"roadmap"==b)&&0!=d.ym;var g=d.jd||_.pa(null);return"satellite"==b?(e?(b=zA(a.W,d.heading),a=null):(b=_.P(DA(a.W.H).j,0).slice(),a=a.ma),new _.yw(b,a,c&&1<_.$k(),_.Iw(d.heading),g)):new qB(_.qw(a.W),c&&1<_.$k(),_.Iw(d.heading),f,g,d.heading)},$B=function(a,b){function c(a,b){if(!b||!b.xc)return b;var c=[];_.zj(c,
b.xc.j);c=new _.Vt(c);_.il(_.It(_.lv(c)),a);return{scale:b.scale,Cd:b.Cd,xc:c}}var d,e=YB(a,"roadmap",a.j,{ym:!1,jd:function(){return c(3,d.get("options"))}}),f=YB(a,"roadmap",a.j,{jd:function(){return c(18,d.get("options"))}}),e=new rB([e,f]),f=YB(a,"roadmap",a.j,{jd:function(){return d.get("options")}});d=new _.Hw(new oB(e,f),a.H,21,"B\u1ea3n \u0111\u1ed3","Hi\u1ec3n th\u1ecb b\u1ea3n \u0111\u1ed3 ph\u1ed1","Xin l\u1ed7i, ch\u00fang t\u00f4i kh\u00f4ng c\u00f3 h\u00ecnh \u1ea3nh \u1edf \u0111\u00e2y.",
_.Sy.roadmap,!1,"m@"+a.V,47,"roadmap",a.T,a.R,a.S,b);ZB(a,d);return d},aC=function(a,b,c){function d(){return h.get("options")}var e=_.y(c),f=YB(a,"satellite",null,{heading:c,jd:d}),g=YB(a,"hybrid",a.j,{heading:c,jd:d}),h=new _.Hw(new rB([f,g]),_.y(c)?new pB(c):a.H,e?21:22,"K\u1ebft h\u1ee3p","Hi\u1ec3n th\u1ecb h\u00ecnh \u1ea3nh c\u00f3 t\u00ean ph\u1ed1","Xin l\u1ed7i, ch\u00fang t\u00f4i kh\u00f4ng c\u00f3 h\u00ecnh \u1ea3nh \u1edf \u0111\u00e2y.",_.Sy.hybrid,e,"m@"+a.V,50,"hybrid",a.T,a.R,a.S,
b);ZB(a,h);return h},bC=function(a,b){var c=_.y(b),d=YB(a,"satellite",null,{heading:b,jd:function(){return e.get("options")}}),e=new _.Hw(d,_.y(b)?new pB(b):a.H,c?21:22,"V\u1ec7 tinh","Hi\u1ec3n th\u1ecb h\u00ecnh \u1ea3nh qua v\u1ec7 tinh","Xin l\u1ed7i, ch\u00fang t\u00f4i kh\u00f4ng c\u00f3 h\u00ecnh \u1ea3nh \u1edf \u0111\u00e2y.",c?"a":_.Sy.satellite,c,null,null,"satellite",a.T,a.R,a.S,null);return e},BB=function(a,b,c){var d=c||{};c=a.ra.__gm.j;var e=null,f=[0,90,180,270];if("hybrid"==b){e=
aC(a,c);b=[];for(var d=0,g=f.length;d<g;++d)b.push(aC(a,c,f[d]));e.j=new tB(e,b)}else if("satellite"==b){e=bC(a);b=[];d=0;for(g=f.length;d<g;++d)b.push(bC(a,f[d]));e.j=new tB(e,b)}else"roadmap"==b&&1<_.$k()&&d.Zm?e=$B(a,c):(f=YB(a,b,a.j,{jd:function(){return e.get("options")}}),e="terrain"==b?new _.Hw(f,a.H,21,"\u0110\u1ecba h\u00ecnh","Hi\u1ec3n th\u1ecb b\u1ea3n \u0111\u1ed3 ph\u1ed1 v\u1edbi \u0111\u1ecba h\u00ecnh","Xin l\u1ed7i, ch\u00fang t\u00f4i kh\u00f4ng c\u00f3 h\u00ecnh \u1ea3nh \u1edf \u0111\u00e2y.",
_.Sy.terrain,!1,"r@"+a.V,63,"terrain",a.T,a.R,a.S,c):new _.Hw(f,a.H,21,"B\u1ea3n \u0111\u1ed3","Hi\u1ec3n th\u1ecb b\u1ea3n \u0111\u1ed3 ph\u1ed1","Xin l\u1ed7i, ch\u00fang t\u00f4i kh\u00f4ng c\u00f3 h\u00ecnh \u1ea3nh \u1edf \u0111\u00e2y.",_.Sy.roadmap,!1,"m@"+a.V,47,"roadmap",a.T,a.R,a.S,c),ZB(a,e,d.Bm));return e},ZB=function(a,b,c){var d=a.ra.__gm;c?b.bindTo("apistyle",c):(b.bindTo("apistyle",d),b.bindTo("mapMaker",a.ra));b.bindTo("authUser",d);_.dg[23]&&b.bindTo("scale",a.ra);a.j.H().addListener(function(){b.notify("epochs")})},
cC=_.k();vA.prototype.U=_.m("j");_.Jf.prototype.j=_.Dj(8,function(a){_.Zc(this.Da,function(b){b(a)})});wA.prototype.U=_.m("j");wA.prototype.getTile=function(){var a=this.j[1];return a?new _.Jt(a):_.Xz};LA.prototype.U=_.m("j");LA.prototype.clearRect=function(){var a=this.j;4 in a&&delete a[4]};
var YA={hue:"h",saturation:"s",lightness:"l",gamma:"g",invert_lightness:"il",visibility:"v",color:"c",weight:"w"},ZA=/^#[0-9a-fA-F]{6}$/,WA={all:0,administrative:1,"administrative.country":17,"administrative.province":18,"administrative.locality":19,"administrative.neighborhood":20,"administrative.land_parcel":21,poi:2,"poi.business":33,"poi.government":34,"poi.school":35,"poi.medical":36,"poi.attraction":37,"poi.place_of_worship":38,"poi.sports_complex":39,"poi.park":40,road:3,"road.highway":49,
"road.highway.controlled_access":785,"road.arterial":50,"road.local":51,transit:4,"transit.line":65,"transit.station":66,"transit.station.rail":1057,"transit.station.bus":1058,"transit.station.airport":1059,"transit.station.ferry":1060,landscape:5,"landscape.man_made":81,"landscape.natural":82,"landscape.natural.landcover":1313,"landscape.natural.terrain":1314,water:6},XA={all:"",geometry:"g","geometry.fill":"g.f","geometry.stroke":"g.s",labels:"l","labels.icon":"l.i","labels.text":"l.t","labels.text.fill":"l.t.f",
"labels.text.stroke":"l.t.s"},nB=[{Zf:108.25,Yf:109.625,ag:49,$f:51.5},{Zf:109.625,Yf:109.75,ag:49,$f:50.875},{Zf:109.75,Yf:110.5,ag:49,$f:50.625},{Zf:110.5,Yf:110.625,ag:49,$f:49.75}],jB=!0;_.r=PA.prototype;_.r.lb=function(){return this.j.lb()};_.r.wc=function(){return this.j.wc()};_.r.release=function(){this.j.release()};_.r.mc=function(){this.j.mc()};
_.r.bc=function(){var a=this.W();if(a&&a.xc){var b=this.V(new _.M(this.Ja.x,this.Ja.y),this.zoom);if(b){for(var c=2==a.scale||4==a.scale?a.scale:1,c=Math.min(1<<this.zoom,c),d=this.qa&&4!=c,e=this.zoom,f=c;1<f;f/=2)e--;var f=256,g;1!=c&&(f/=c);d&&(c*=2);1!=c&&(g=c);c=new _.zw(a.xc);_.Bw(c,0);g&&(AA(c.j).j[4]=g);_.Cw(c,b,e,f);if(e=this.S(b,this.zoom))xA(c,e),_.za(this.R)&&_.Gw(c,this.R),e=this.T,b=e[(b.x+2*b.y)%e.length],b+="pb="+(0,window.encodeURIComponent)(_.kv(c.j)).replace(/%20/g,"+"),null!=a.Cd&&
(b+="&authuser="+a.Cd),b=this.ma(b),this.H==b?this.j.bc():(this.H=b,this.j.setUrl(b))}else this.H="",this.j.setUrl("")}};_.r=QA.prototype;_.r.lb=_.m("H");_.r.wc=function(){return MA(this.j,function(a){return a.wc()})};_.r.release=function(){_.Ob(this.j,function(a){a.release()});this.R()};_.r.mc=function(){_.Ob(this.j,function(a){a.mc()})};_.r.bc=function(){_.Ob(this.j,function(a){a.bc()})};var GB={bluetooth:"-b",cellular:"-c",ethernet:"-e",none:"-n",wifi:"-wf",wimax:"-wm",other:"-o"};_.v(SA,_.H);
SA.prototype.input_changed=function(){this.get("idle")&&this.set("idle",!1);this.j&&window.clearTimeout(this.j);this.j=window.setTimeout((0,_.u)(this.H,this),this.R)};SA.prototype.H=function(){this.j=null;this.set("idle",!0)};_.v(VA,_.H);VA.prototype.changed=function(a){if("available"!=a){a=this.get("viewport");var b=this.get("featureRects");a=this.j(a,b);null!=a&&a!=this.get("available")&&this.set("available",a)}};_.v(aB,_.H);
aB.prototype.mapTypeId_changed=function(){var a=this.get("mapTypeId");this.R(a)};aB.prototype.setMapTypeId=function(a){this.R(a);this.set("mapTypeId",a)};
aB.prototype.R=function(a){var b=this.H.get(a);if(!b||b!=this.T){this.S&&(_.F.removeListener(this.S),this.S=null);var c=(0,_.u)(this.R,this,a);a&&(this.S=_.F.addListener(this.H,a.toLowerCase()+"_changed",c));b&&b instanceof _.Ng?(a=b.j,this.set("styles",b.get("styles"))):this.set("styles",null);bB(this,a);this.j&&this.j.unbindAll();this.j=new _.Jw(["mapType"],"maxZoom",function(a){return(a=a||b)&&a.maxZoom});b&&b instanceof _.Hw&&b.j&&this.j.bindTo("mapType",b.j);this.bindTo("maxZoom",this.j);this.set("minZoom",
b&&b.minZoom);this.T=b}};_.v(eB,_.H);eB.prototype.S=function(a){var b=this.j,c=cB(this,this.H.getAt(a));b.splice(a,0,c);dB(this)};eB.prototype.T=function(a){var b=this.j;fB(b[a]);b.splice(a,1);dB(this)};eB.prototype.V=function(a){fB(this.j[a]);var b=cB(this,this.H.getAt(a));b.set("zIndex",a);this.j[a]=b};gB.prototype.ma=function(){hB(this,"visreq",function(){_.gg(this.j,"visreq")})};gB.prototype.qa=function(){hB(this,"visres",function(){_.gg(this.j,"visres")})};
gB.prototype.V=function(){hB(this,"firsttile",function(){var a={firsttile:void 0};hB(this,"firstpixel",function(){a.firstpixel=void 0});_.fg(this.j,a)})};gB.prototype.W=function(){hB(this,"tilesloaded",function(){var a={tilesloaded:void 0};hB(this,"allpixels",function(){a.allpixels=void 0});_.fg(this.j,a)})};lB.prototype.T=function(a,b){return this.S(this.R.T(a,b))};lB.prototype.j=function(a){return this.S(this.R.j(a))};lB.prototype.H=function(){return this.R.H()};_.v(mB,_.H);
mB.prototype.offset_changed=function(){this.set("newCenter",this.get("center"));var a=this.get("projectionBounds"),b=this.get("offset");if(a&&b){var c=this.get("div");_.Wl(c,new _.M(a.ua-b.width,a.va-b.height));_.am(c)}};pB.prototype.fromLatLngToPoint=function(a,b){var c=this.R.fromLatLngToPoint(a,b);OA(c,this.j.heading());c.y=(c.y-128)/_.Wz+128;return c};
pB.prototype.fromPointToLatLng=function(a,b){var c=this.S;c.x=a.x;c.y=(a.y-128)*_.Wz+128;OA(c,360-this.j.heading());return this.R.fromPointToLatLng(c,b)};pB.prototype.getPov=_.m("j");_.v(tB,_.H);tB.prototype.heading_changed=function(){var a=this.get("heading");if(_.y(a)){var b;b=_.Na(a,0,360);b=this.j*Math.round(b/this.j);a!==b?this.set("heading",b):sB(this)}};tB.prototype.tilt_changed=function(){sB(this)};
uB.prototype.H=function(a,b){for(var c=this.j,d=new _.M(a.x%(1<<b),a.y),e=0;e<c.length;++e){var f=c[e];if(!(f.minZoom>b||f.maxZoom<b)){var g=_.w(f.hb);if(0==g)return f.j;for(var h=f.maxZoom-b,l=0;l<g;++l){var n=f.hb[l];if(_.Fj(new _.Lf([new _.M(n.ua>>h,n.va>>h),new _.M(1+(n.Aa>>h),1+(n.Ba>>h))]),d))return f.j}}}return null};_.v(DB,_.H);
DB.prototype.getPrintableImageUri=function(a,b,c,d,e){var f=this.get("mapType");if(2048<a*(e||1)||2048<b*(e||1)||!(f instanceof _.Hw))return null;var g=d||this.get("zoom");if(null==g)return null;var h=c||this.get("center");if(!h)return null;c=f.get("options");if(!c.xc)return null;d=new _.zw(c.xc);_.Bw(d,0);var l=this.H.j(g);l&&xA(d,l);if("hybrid"==f.Za){_.nv(d.j);for(f=_.fd(d.j.j,1)-1;0<f;--f){var l=uA(d.j,f),n=uA(d.j,f-1);_.zj(l.j,n?n.U():null)}f=uA(d.j,0);f.j[0]=1;1 in f.j&&delete f.j[1];2 in f.j&&
delete f.j[2]}if(2==e||4==e)AA(d.j).j[4]=e;e=_.mv(d.j);e.j[3]=e.j[3]||[];e=new _.Rt(e.j[3]);e.setZoom(g);e.j[2]=e.j[2]||[];g=new _.to(e.j[2]);f=yA(h.lat());g.j[0]=f;h=yA(h.lng());g.j[1]=h;e.j[0]=e.j[0]||[];h=new _.St(e.j[0]);h.j[0]=a;h.j[1]=b;a=this.j;a+="pb="+(0,window.encodeURIComponent)(_.kv(d.j)).replace(/%20/g,"+");null!=c.Cd&&(a+="&authuser="+c.Cd);return a};_.v(EB,_.H);EB.prototype.changed=function(a){"mapType"!=a&&"style"!=a&&this.notify("style")};
EB.prototype.getStyle=function(){var a=[],b,c=this.get("mapType");c instanceof _.Hw&&c.H&&(b=new _.hl,_.il(b,c.H),a.push(b));b=new _.hl;_.il(b,37);_.Mk(_.jl(b),"smartmaps");a.push(b);this.get("mapMaker")&&(b=new _.hl,_.il(b,33),a.push(b));this.j.get().forEach(function(b){b.R&&a.push(b.R)});return a};_.v(KB,_.H);KB.prototype.H=function(){var a=LB(this);this.get("attributionText")!=a&&this.set("attributionText",a)};
NB.prototype.W=function(a){if(_.fd(a.j,0)){this.S={};this.R={};for(var b=0;b<_.fd(a.j,0);++b){var c,d=b;c=new wA(_.P(a.j,0)[d]);var e=c.getTile(),d=e.getZoom(),f;f=e.j[1];f=null!=f?f:0;e=e.j[2];e=null!=e?e:0;c=c.j[2];c=null!=c?c:0;var g=this.S;g[d]=g[d]||{};g[d][f]=g[d][f]||{};g[d][f][e]=c;this.R[d]=Math.max(this.R[d]||0,c)}this.V.j(null)}};NB.prototype.T=function(a,b){var c=this.S,d=a.x,e=a.y;return c[b]&&c[b][d]&&c[b][d][e]||0};NB.prototype.j=function(a){return this.R[a]||0};NB.prototype.H=_.m("V");
_.v(OB,_.H);OB.prototype.changed=function(a){if("apistyle"!=a&&"hasCustomStyles"!=a){var b=this.get("mapTypeStyles")||this.get("styles");this.set("hasCustomStyles",_.w(b));var c=[];_.dg[13]&&c.push({featureType:"poi.business",elementType:"labels",stylers:[{visibility:"off"}]});_.Ra(c,b);this.j=$A(c);"styles"==a&&this.notify("apistyle")}};OB.prototype.getApistyle=_.m("j");_.v(QB,_.H);QB.prototype.changed=function(a){"zoomRange"!=a&&PB(this)};_.v(RB,_.H);
RB.prototype.changed=function(a){if("maxZoomRects"==a||"latLng"==a){a=this.get("latLng");var b=this.get("maxZoomRects");if(a&&b){for(var c=void 0,d=0,e;e=b[d++];)e.hb.contains(a)&&(c=Math.max(c||0,e.maxZoom));a=c;a!=this.get("maxZoom")&&this.set("maxZoom",a)}else this.set("maxZoom",void 0)}};_.v(WB,_.H);WB.prototype.immutable_changed=function(){var a=this,b=a.get("immutable"),c=a.H;b!=c&&(_.Ja(a.j,function(d){(c&&c[d])!==(b&&b[d])&&a.set(d,b&&b[d])}),a.H=b)};cC.prototype.H=function(a,b,c,d,e,f){function g(){var b=a.get("streetView");b?(a.bindTo("svClient",b,"client"),b.__gm.bindTo("fontLoaded",Xb)):(a.unbind("svClient"),a.set("svClient",null))}var h=_.hf(_.kf(_.R)),l=a.__gm,n=a.getDiv();_.F.addDomListenerOnce(n,"mousedown",function(){_.$m(a,"Mi")},!0);var p=new _.Ly(n,b,{Ci:!0,bj:_.Kj(_.kf(_.R))}),q=p.S;_.em(p.j,0);_.F.forward(a,"resize",n);l.set("panes",p.V);l.set("innerContainer",p.H);var t=TB(e,a,new _.wx(p,"size"),c&&c.R),C=new RB,B=vB(),z,D;(function(){var b=
EA(_.Hj()),c=a.get("noPerTile")&&_.dg[15],d=new NB;z=UB(d,b,a,c);D=new _.xy(h,C,B,l.ya,c?null:d,!!a.j,t)})();D.bindTo("tilt",a);D.bindTo("heading",a);D.bindTo("bounds",a);D.bindTo("zoom",a);D.bindTo("mapMaker",a);D.bindTo("size",l);e=new XB(CA(),a,z);CB(e,a.mapTypes,b.enableSplitTiles);var J=new _.bd(!1);_.R&&_.Ij()||(l.set("eventCapturer",p.R),l.set("panBlock",p.T));_.Vk()&&_.Kl()||_.L("onion",function(b){b.H(a,z)});var E=new _.Dx(q,p.W,t);e=new _.Jw(["blockingLayerCount","staticMapLoading"],"waitWithTiles",
function(a,b){return!!a||!!b});e.bindTo("blockingLayerCount",l);E.bindTo("waitWithTiles",e);E.set("panes",p.V);E.bindTo("styles",a);_.dg[20]&&E.bindTo("animatedZoom",a);_.dg[35]&&(_.My(a),_.Ny(a));var G=new _.ay;G.bindTo("tilt",a);G.bindTo("zoom",a);G.bindTo("mapTypeId",a);G.bindTo("aerial",B.obliques,"available");l.bindTo("tilt",G);var K=AB(a);D.bindTo("mapType",K);var ba=new KB(l.ya);_.F.addListener(ba,"attributiontext_changed",function(){a.set("mapDataProviders",ba.get("attributionText"))});e=
new OB;e.bindTo("styles",a);e.bindTo("mapTypeStyles",K,"styles");l.bindTo("apistyle",e);l.bindTo("hasCustomStyles",e);e=new EB(l.j);e.bindTo("mapMaker",a);e.bindTo("mapType",K);l.bindTo("style",e);var ca=new _.fx;l.set("projectionController",ca);E.bindTo("size",p);E.bindTo("projection",ca);E.bindTo("projectionBounds",ca);E.bindTo("mapType",K);ca.bindTo("projectionTopLeft",E);ca.bindTo("offset",E);ca.bindTo("latLngCenter",a,"center");ca.bindTo("size",p);ca.bindTo("projection",a);E.bindTo("fixedPoint",
ca);a.bindTo("bounds",ca,"latLngBounds",!0);l.set("mouseEventTarget",{});e=new _.Vx(_.X.R,p.H);e.bindTo("title",l);var Va=SB(p.H,q,a,E,ca,f,e,J);c&&(f=VB(a,q),c.bindTo("div",f),c.bindTo("center",f,"newCenter"),c.bindTo("zoom",Va),c.bindTo("tilt",l),c.bindTo("size",l));l.bindTo("zoom",Va);l.bindTo("center",a);l.bindTo("size",p);l.bindTo("mapType",K);l.bindTo("offset",E);l.bindTo("layoutPixelBounds",E);l.bindTo("pixelBounds",E);l.bindTo("projectionTopLeft",E);l.bindTo("projectionBounds",E,"viewProjectionBounds");
l.bindTo("projectionCenterQ",ca);a.set("tosUrl",_.dz);c=MB();c.bindTo("bounds",E,"pixelBounds");l.bindTo("pixelBoundsQ",c,"boundsQ");c=new WB({projection:1});c.bindTo("immutable",l,"mapType");f=new _.ex({projection:new _.Kf});f.bindTo("projection",c);a.bindTo("projection",f);_.F.forward(l,"panby",E);_.F.forward(l,"panbynow",E);_.F.forward(l,"panbyfraction",E);_.F.addListener(l,"panto",function(b){if(b instanceof _.I)if(a.get("center")){b=ca.fromLatLngToDivPixel(b);var c=ca.get("offset")||_.hh;b.x+=
Math.round(c.width)-c.width;b.y+=Math.round(c.height)-c.height;_.F.trigger(E,"panto",b.x,b.y)}else a.set("center",b);else throw Error("panTo: latLng must be of type LatLng");});_.F.forward(l,"pantobounds",E);_.F.addListener(l,"pantolatlngbounds",function(a){if(a instanceof _.Gd)_.F.trigger(E,"pantobounds",BA(ca,a));else throw Error("panToBounds: latLngBounds must be of type LatLngBounds");});_.F.addListener(Va,"zoom_changed",function(){Va.get("zoom")!=a.get("zoom")&&(a.set("zoom",Va.get("zoom")),
_.en(a,"Mm"))});var wa=new QB;wa.bindTo("mapTypeMaxZoom",K,"maxZoom");wa.bindTo("mapTypeMinZoom",K,"minZoom");wa.bindTo("maxZoom",a);wa.bindTo("minZoom",a);wa.bindTo("trackerMaxZoom",C,"maxZoom");Va.bindTo("zoomRange",wa);E.bindTo("zoomRange",wa);Va.bindTo("draggable",a);Va.bindTo("scrollwheel",a);Va.bindTo("disableDoubleClickZoom",a);var Xb=new _.Iy(_.Vl(n));l.bindTo("fontLoaded",Xb);c=l.R;c.bindTo("scrollwheel",a);c.bindTo("disableDoubleClickZoom",a);g();_.F.addListener(a,"streetview_changed",g);
if(!a.j){var Cc=function(){_.L("controls",function(b){var c=new b.Sh(p.j);l.set("layoutManager",c);E.bindTo("layoutBounds",c,"bounds");b.$n(c,a,K,p.j,ba,B.report_map_issue,wa,G,ca,p.R,z,J);b.ao(a,p.H);(c=a.getDiv())&&b.Tj(c)})};if(_.Vk()){var rc=_.sv.Fc().j;c=new _.Hy(l.j);c.bindTo("gid",rc);c.bindTo("persistenceKey",rc);_.$m(a,"Sm");c=function(){rc.get("gid")&&_.$m(a,"Su")};c();_.F.addListener(rc,"gid_changed",c)}var $d=_.F.addListener(E,"tilesloading_changed",function(){E.get("tilesloading")&&($d.remove(),
Cc())});_.F.addListenerOnce(E,"tilesloaded",function(){_.L("util",function(b){b.H.j();window.setTimeout((0,_.u)(b.j.H,b.j),5E3);b.S(a)})});_.$m(a,"Mm");b.v2&&_.$m(a,"Mz");_.bn("Mm","-p",a,!(!a||!a.j));zB(a,K);_.en(a,"Mm");_.pm(function(){_.en(a,"Mm")});yB(a);n&&IB(new JB(n),a,function(){return 0!=a.get("draggable")})}xB(a);var ae=EA(_.Hj());b=new XB(CA(),a,new lB(z,function(a){return a||ae}));FB(b,a.overlayMapTypes);wB(a,p.V.mapPane);_.dg[35]&&l.bindTo("card",a);a.j||HB(a);d&&window.setTimeout(function(){_.F.trigger(a,
"projection_changed");_.sa(a.get("bounds"))&&_.F.trigger(a,"bounds_changed");_.F.trigger(a,"tilt_changed");_.sa(a.get("heading"))&&_.F.trigger(a,"heading_changed")},0);_.dg[15]&&(d=_.qw(_.rw()),d=new DB(d[0],z),d.bindTo("mapType",K),d.bindTo("center",a),d.bindTo("zoom",l),a.getPrintableImageUri=(0,_.u)(d.getPrintableImageUri,d),a.setFpsMeasurementCallback=(0,_.u)(E.setFpsMeasurementCallback,E),l.bindTo("authUser",a),a.bindTo("tilesloading",E))};
cC.prototype.fitBounds=function(a,b){function c(){var c=_.Sf(a.getDiv());c.width-=80;c.width=Math.max(1,c.width);c.height-=80;c.height=Math.max(1,c.height);var e=a.getProjection(),f=b.getSouthWest(),g=b.getNorthEast(),h=f.lng(),l=g.lng();h>l&&(f=new _.I(f.lat(),h-360,!0));f=e.fromLatLngToPoint(f);h=e.fromLatLngToPoint(g);g=Math.max(f.x,h.x)-Math.min(f.x,h.x);f=Math.max(f.y,h.y)-Math.min(f.y,h.y);c=g>c.width||f>c.height?0:Math.floor(Math.min(_.Tk(c.width+1E-12)-_.Tk(g+1E-12),_.Tk(c.height+1E-12)-_.Tk(f+
1E-12)));g=_.Jk(e,b,0);e=_.Kk(e,new _.M((g.ua+g.Aa)/2,(g.va+g.Ba)/2),0);_.y(c)&&(a.setCenter(e),a.setZoom(c))}a.getProjection()?c():_.F.addListenerOnce(a,"projection_changed",c)};cC.prototype.j=function(a,b,c,d,e,f){var g=_.uw(a,b,c,d,{Lc:f});_.Lc(function(){g.setUrl(e)});return g};_.lc("map",new cC);});
